name: Node CI

on: [push,pull_request]
#   push:
#     branches: 
#       - master
#       - release
#   pull_request:
#     branches: 
#       - '**'
jobs:
  build:
    name: first build job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
          
    - name: Scan for A11y issues
      uses: microsoft/accessibility-insights-action@master
      with:
        scan-url-relative-path: /
        repo-token: ${{ secrets.GITHUB_TOKEN }}  
        
    - name: Upload report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: reports
      # Directory containing files to upload
        path: ${{ github.workspace }}/_accessibility-reports
    - name: Install dependencies
      run: yarn install

    - name: Add PR Comment
      uses: mshick/add-pr-comment@v1
      with:
        # the message to print
        message: 'message from add-pr-comment'
        # a github token for API access
        repo-token: ${{secrets.GITHUB_TOKEN}}
        # allow messages to be repeated
        allow-repeats: true
    
    - name: PR Comment
      uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        # input description here
        myInput: 'pr comment from github-actions-up-and-running/pr-comment'
    
    - name: Release
      #uses: brpaz/action-semantic-release@v1
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release')
    
